# Generated by Django 5.0 on 2024-12-13 02:29

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('uniqueLink', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('timeUploaded', models.DateTimeField(default=datetime.datetime.now)),
                ('fileSize', models.IntegerField()),
                ('fileType', models.CharField(max_length=255)),
            ],
        ),
    ]
