# Generated by Django 5.0 on 2024-12-13 02:48

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='timeUploaded',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uniqueLink',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
