# Generated by Django 5.0 on 2024-12-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_file_filename_alter_file_filesize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to='Files'),
        ),
    ]
