# Generated by Django 5.0 on 2024-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileSize',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
